# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 157d170e71097923b88c685a543282d12929d479da9ad0643b1c9437f9c1672167a7b686b35a1be5e21218678c7d093ad7e9bdf560b28f056667f22323ebf7cb

test:
  secret_key_base: c0978b9791b29d35a0a8de7909ba6c252fd5f3eecf6b892a0cc490aa0834ebc21906f558bce56b3630fe23dd20bf6153a2743336b6d63c9f62fcc20e3cdc42dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
